apiVersion: v1
kind: "Deployment"
metadata:
  name: rcee-deployment
spec:  
  selector:
    matchLabels: 
      app: rcee-app
  template:
    selector:
      labels:
        app: rcee-app
    replicas: 2
    spec:
      containers:
      - name: "RCEE Server"
        image: mrimann/rcee-server
        containerPort: 3000
      - name: "RCEE Worker"
        image: mrimann/rcee-worker
        containerPort: 4000