
services:
  amqp: 
    image: rabbitmq:3.13-alpine
    container_name: rcee-amqp-inst
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
    - rcee-conn

  server:
    build:
      context: server
    command: /bin server
    environment:
    - AMQP_URL=amqp://guest:guest@amqp/
    image: mrimann/rcee-server
    container_name: rcee-server-inst
    depends_on:
    - amqp
    ports:
    - "8080:8080"
    networks:
    - rcee-conn
  
  worker:
    build:
      context: server
    command: /bin worker
    container_name: rcee-worker-inst
    depends_on:
    - amqp
    environment:
    - AMQP_URL=amqp://guest:guest@amqp/
    image: mrimann/rcee-worker
    networks:
    - rcee-conn
 
networks:
  rcee-conn:

  
