apiVersion: v1
kind: "Service"
metadata: 
  name: rcee-service
spec:
  selector: 
    app: rcee-app
  ports:
  - name: "Server port"
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
  - name: "Worker port"
    protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30002
  type: NodePort
  
 