name: Deploy Docker Image

on: [push]


jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Docker Buildx for Building Image
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker image
      run: |
        docker compose pull amqp
        docker compose -p rcee build 
        docker compose  push 
     - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
    - name: Configure the AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with: 
        version: 'latest'
    - name: Update kubeconfig
      run: |
        aws eks get-token --cluster-name ${{ secrets.CLUSTER_NAME }} | kubectl apply -f -
        aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml

